Add auto-formatting
aiven/pglookout pull request #85
Opened 2022-10-18 09:50 UTC by alexole

2022-10-18 10:39 UTC, kmichel-aiven requested changes, later dismissed
All our other repositories are using black instead of yapf, I think we should use that here too.

2022-10-18 11:11 UTC, alexole commented
Well, I don't mind, but I don't think all are using black, pghoard still uses yapf.

2022-10-18 11:16 UTC, kmichel-aiven commented
> Well, I don't mind, but I don't think all are using black, pghoard still uses yapf.

Ah, you're right, rohmu has already switched to black but not all repos.

I'd still push for black though, I think it's the general direction we're taking everywhere (and the rest of the Python community).

2022-10-19 09:37 UTC, kmichel-aiven approved these changes

2022-10-19 09:37 UTC, merged